// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtPXSksTCR_EtAlrnl9aAElXtnMfRORqQ',
    appId: '1:906887402326:web:bb24a0fda012258318fcf7',
    messagingSenderId: '906887402326',
    projectId: 'dhorefelshaheen',
    authDomain: 'dhorefelshaheen.firebaseapp.com',
    storageBucket: 'dhorefelshaheen.firebasestorage.app',
    measurementId: 'G-79354NXFXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuTpfoN3hM7slWuSnzzhP9iOtZpY1TbwE',
    appId: '1:906887402326:android:87626203496fc3cd18fcf7',
    messagingSenderId: '906887402326',
    projectId: 'dhorefelshaheen',
    storageBucket: 'dhorefelshaheen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_g_pwuAGJ5wjeLJoZsHHjqGVcANor1JY',
    appId: '1:906887402326:ios:8a098dd179c78b8c18fcf7',
    messagingSenderId: '906887402326',
    projectId: 'dhorefelshaheen',
    storageBucket: 'dhorefelshaheen.firebasestorage.app',
    iosBundleId: 'com.arrijal.dhorefelshaheen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_g_pwuAGJ5wjeLJoZsHHjqGVcANor1JY',
    appId: '1:906887402326:ios:8a098dd179c78b8c18fcf7',
    messagingSenderId: '906887402326',
    projectId: 'dhorefelshaheen',
    storageBucket: 'dhorefelshaheen.firebasestorage.app',
    iosBundleId: 'com.arrijal.dhorefelshaheen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtPXSksTCR_EtAlrnl9aAElXtnMfRORqQ',
    appId: '1:906887402326:web:0a7dc0a11b760e1918fcf7',
    messagingSenderId: '906887402326',
    projectId: 'dhorefelshaheen',
    authDomain: 'dhorefelshaheen.firebaseapp.com',
    storageBucket: 'dhorefelshaheen.firebasestorage.app',
    measurementId: 'G-9KD49Z2KD8',
  );
}
